### ISSUE TITLE
Creates 20+ GB syslog

### ISSUE THREAD

**Issue by MernokUr** [BigE/desk-changer#11]
Hi Eric!
I got a warning, that my disk is almost full. Reason was the syslog file, more than 20Gb (yes, gigabyte).
The most of the entires were from your plugin: "file is too similar, grabbing a different one"

**Comment by BigE** [comment]
I've updated the daemon so that this message is a lower priority and shouldn't show up as often. This should prevent it from showing up in the syslog, at least, and prevent the log from filling up so quickly! Sorry about that! Thanks for the bug report.
