### ISSUE TITLE
Doesn't allow scaling of wallpapers

### ISSUE THREAD

**Issue by rawkode** [BigE/desk-changer#12]
Wallpapers don't scale, instead are shown centered as desktop wallpaper

**Comment by BigE** [comment]
This is not a function of the desk-changer software, but actually a setting option in Gnome itself. To change the background, the desk-changer daemon just changes a settings key of `org.gnome.desktop.background.picture-uri` to the image path and Gnome takes care of centering/scaling/rendering. If you want to update how your wallpapers are drawn in Gnome, you can change the setting yourself. Unfortunately, there is not a way implemented in the GUI, so you'll have to use `dconf-editor` if you want a GUI, or use `gsettings` from the command line.

I personally prefer dconf-editor as its just easier to use, but the change is just as easy with gsettings. To use gsettings, just simply open up a terminal window. First, you can check what your current settings are by typing:
`gsettings get org.gnome.desktop.background picture-options`
This will output what it is currently set to. Then to change it, type in the following command:
`gsettings set org.gnome.desktop.background picture-options scaled`
This will change Gnome to draw your wallpapers in a scaled mode.
> Determines how the image set by wallpaper_filename is rendered. Possible values are "none", "wallpaper", "centered", "scaled", "stretched", "zoom", "spanned".

Using this you can change how the background is drawn. Hope this helps!
