### ISSUE TITLE
If the system extension list is long, the preview of the wallpaper is ugly.

### ISSUE THREAD

**Issue by wangxa** [BigE/desk-changer#15]
See the screenshot, my extension list is very long, so desk-changer smartly re-size the preview of the wallpaper. It's good, but it looks not so beautiful.

![desk-changer-screenshot](https://cloud.githubusercontent.com/assets/1250269/22825463/46f896ea-ef85-11e6-9eb1-9a0249c8c0fc.jpg)

**Comment by BigE** [comment]
I have yet to reproduce this... I need to get things into a VM and play with the size of the screen to reproduce. I'm not yet sure how to solve this either. I'm assuming the widget is simply limited to the space available and I'm not sure if I can determine that prior to drawing the preview. I'll do some investigation soon and update then.

**Comment by wangxa** [comment]
I think it was the issue of gnome-shell and not your extension's problem. When I submitted this issue report, Gnome shell was possible to open two or more sub menus at the same time, but after updating Gnome shell, only one sub menu keeps open. See my screenshot. So this problem is gone. You can close this ticket.

![1](https://cloud.githubusercontent.com/assets/1250269/25457657/ed40bb52-2ace-11e7-8057-50b635c3186b.png)

**Comment by BigE** [comment]
Thanks for the feedback! Closing this ticket.
