### ISSUE TITLE
"TypeError: redeclaration of let label" with Gnome 3.24

### ISSUE THREAD

**Issue by papanito** [BigE/desk-changer#18]
With latest Gnome-Shell 3.24 I get an exception when I want to enter the "DeskChanger Settings"

```
TypeError: redeclaration of let label

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
```

**Comment by BigE** [comment]
Thanks for reporting the error! I'll have this fixed in the next release of the extension. I'm currently working through rewriting some things and fixing other errors so I won't release the fix immediately. If I can't get the new stuff done by the end of the weekend, I'll release this fix Monday.

**Comment by BigE** [comment]
This is now fixed in [Version 22](https://github.com/BigE/desk-changer/releases/tag/version-22). It will be available on the gnome extension site once the update is approved. Thanks again for your submission!
