### ISSUE TITLE
Toggle desks on key-combination

### ISSUE THREAD

**Issue by vixsomnis** [BigE/desk-changer#2]
I'd like to be able to switch backgrounds on a key-press. How difficult is this to implement? I can attempt this, but I'm just starting out with javascript (and gnome extensions), so it will take me a while to figure out the codebase and API.

**Comment by BigE** [comment]
It shouldn't be too hard to implement... I'll have to look at other extensions and see how its done there. I was wanting to do this but hadn't decided on any set of key combinations yet... any suggestions would be welcome.

**Comment by vixsomnis** [comment]
A super+KEY combo is probably best, as all of the major gnome shortcuts for managing the interface use the windows key. User selectable? super+b works for me.

**Comment by BigE** [comment]
I'm going to have to decide if I want to hotkey some other functionality too... I'd like all the functional buttons of the extension to have hotkeys and the hotkeys to be user customizable. I'll look to see if super+b is taken by anything else common and go from there. Thanks for the recommendations!
