### ISSUE TITLE
L10N - would it be possible to translate this tool?

### ISSUE THREAD

**Issue by Jibec** [BigE/desk-changer#21]
hi, I would really like to translate this application, would it be possible to add the localization support?
In addition, I assume directly connecting you project to https://hosted.weblate.org or whatever translation platform of your choice would be great!

thanks a lot for your help!

**Comment by BigE** [comment]
I would love to add localization support, great idea! I'll work this into the next feature release that I make. Not sure when that will be, but I'll update this as I work through it. Thanks!

**Comment by Jibec** [comment]
I glad to see this! Please let me know when I can send you a translated version so we can test this together :)

**Comment by BigE** [comment]
I've updated the file paths in the develop branch, please let me know if you can test this still. Thanks!

**Comment by Jibec** [comment]
He are the files, I don't have an example to know where to put them in git :(
"Remember the profiles current/next wallpaper" => what are we talking about?
"DeskChanger" => I understand we should not translate it
"LockScreen" => it's written like we shouldn't translate it, but I feel like we should translate it, isn't it?
"Show Preview as Icon" => is Preview translatable?

Github doesn't accept po files in issues, so it's txt...
[desk-changer.fr.txt](https://github.com/BigE/desk-changer/files/1310787/desk-changer.fr.txt)
[desk-changer-daemon.fr.txt](https://github.com/BigE/desk-changer/files/1310786/desk-changer-daemon.fr.txt)

Next step for your software : add a desktop file and make it translatable :p
Next step for translation : use a translation platform ;)

**Comment by BigE** [comment]
> He are the files, I don't have an example to know where to put them in git :(

Just put the po files into the po folder under the language you're translating. For this, just create po/fr/ and place the .po files in that folder.

> "Remember the profiles current/next wallpaper" => what are we talking about?

This is the daemon's ability to remember the currently set wallpaper and the next in queue wallpaper when it shuts down. Thus, when it is started again, it begins where it left off.

> "DeskChanger" => I understand we should not translate it

No, this is the name of the extension.

> "LockScreen" => it's written like we shouldn't translate it, but I feel like we should translate it, isn't it?

Might just dig into gnome and see how they handle it? I took the terminology from them directly.

> "Show Preview as Icon" => is Preview translatable?

I would assume so, the preview is just a display of the next wallpaper to be set to the desktop.

> Github doesn't accept po files in issues, so it's txt...
> desk-changer.fr.txt
> desk-changer-daemon.fr.txt
> 
> Next step for your software : add a desktop file and make it translatable :p
> Next step for translation : use a translation platform ;)

I need to get a build process going in the project to automate a few things... this will be one of them. Thanks for the time and effort on this!

To get all this added, just add your po files in the folders discussed above and create a pull request. Once that's done, I can start working on a build process to automate the creation of the files for the extension itself. Once that's done, I can make a release with the new translations. Thanks!

**Comment by BigE** [comment]
Translations provided are in the newest release. Please feel free to fork and submit merge requests from here on out. I've also added a basic Makefile for build support... it should get things working at the least. Thanks for the contribution!

**Comment by Jibec** [comment]
thanks for the attribution 👍
