### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by HROMANO** [BigE/desk-changer#26]
Pictures are not correctly rotated when displayed. They are all landscaped, even if exif info is portrait.

**Comment by BigE** [comment]
This is outside of the control of the extension as a whole and cannot be fixed here. The daemon simply changes a settings key for Gnome that controls what image is displayed as the background, and does not actually control the background image or how it is displayed. This is done by Gnome itself, which you can see happening yourself by simply running the command `gsettings set org.gnome.desktop.background picture-uri file:///path/to/your/image.png` This is essentially all the extension itself does.
