### ISSUE TITLE
Change on every new hour

### ISSUE THREAD

**Issue by sojusnik** [BigE/desk-changer#3]
First of all, thanks for creating this nice extension!

To make it even better, it would be great to have an option to change the wallpaper on every new hour, to get a feeling for the time, especially when you are working for several hours in a "flow" condition :)
It's not about changing the wallpaper every hour or so, but when a new hour starts, like 14:00, 15:00 and so on.

Is there actually a way to completely disable the shortcuts for changing to wallpapers, to avoid accidental usage?

Thanks in advance!

**Comment by BigE** [comment]
I created #4 to track the key shortcuts better, I'll provide and update soon for that once I get some time. It would be possible to change the wallpaper on the hour or a set time specifically. This would require a bit of reworking on how the timer itself works though.

I would like to add this functionality, unfortunately I'm just not sure how quickly I'll be able to get to something like this. I'll start looking into it, but pull requests are welcome if anyone else would like to tackle this until I can.

**Comment by sojusnik** [comment]
Great news, thanks!

**Comment by BigE** [comment]
Marking this as closed, finally. I've implemented an hourly method that you can now get to by pressing the third button in the controls. When the clock is shown on the button, the daemon will now be in "hourly" mode which will update the wallpaper within 10 seconds of the beginning of the hour. Let me know how this works out for you. I'll have the extension uploaded to https://extensions.gnome.org shortly for review, then once approved you should be able to update from there. Thanks for the feature request!
