### ISSUE TITLE
Daemon crashes

### ISSUE THREAD

**Issue by curvatura99** [BigE/desk-changer#30]
Since the update the daemon now crashes with the following error:

$ ./desk-changer-daemon.py 

(desk-changer-daemon.py:9426): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.screensaver.background' is not installed

Trace/breakpoint trap (core dumped)

This occurs on two different machines running Ubuntu 17.04 64-bit with GNOME Shell 3.24.2. Previous version of the extension works without issue.

**Comment by BigE** [comment]
Typo on my part here... I'll get this cleaned up and another release out shortly with the fix. For a workaround, just disable updating the lock screen. Doing that should temporarily solve the problem without a downgrade.

**Comment by curvatura99** [comment]
Thanks for the quick response. Your extension is a good addition to Gnome and would be missed if it didn't work.

**Comment by BigE** [comment]
This should be fixed in the latest release. It might take a couple of days for the extension site to approve the update. Thanks for the report!
