### ISSUE TITLE
TypeError: Main.screenShield is null

### ISSUE THREAD

**Issue by DNAiel** [BigE/desk-changer#31]
Hey,

I'm unable to enable this extension using 3.26, extensions.gnome.org and gnome-tweak-tool report an 'error loading extension'. Checking lg gives TypeError: Main.screenShield is null. I imagine this is because I use LightDM as a login manager instead of GDM. Searching encountered a similar error in another extension [here](https://github.com/rockon999/dynamic-panel-transparency/issues/7).

Thanks for any available assistance if this can be addressed.

**Comment by BigE** [comment]
Good find, thanks for reporting this! I'll have to add support to the extension to check if the lockscreen exists before showing any support for that. Thanks again!
