### ISSUE TITLE
Exstension sudenly quit working...

### ISSUE THREAD

**Issue by mcoyle1960** [BigE/desk-changer#32]
Running fairly standard Ubuntu-Gnome 17.04 install. No dev repositories. Not sure exactly when, but probably within the past week, the extension quit working. I can open prefs, but never see the  Preview Icon. 

Tried uninstall/reinstall. No change. 

Let me know if there are any logs I can send to help.  Thanks.

**Comment by BigE** [comment]
Can you tell me what version of the extension you have installed by taking a look inside the metadata.json file? It should be located in your home folder under `~/.local/share/gnome-shell/extensions/desk.changer@eric.gach.gmail.com/metadata.json` You can also grab logs from your system for gnome-shell... I believe Ubuntu uses systemd by default, which means you would have to use `journalctl` to pull logs for gnome-shell.

There was a previous issue #31 reported when using a login manager like lightdm, or something other than gdm. This has been fixed, but is not yet released on the extension website as its still pending review. This could result in the same issue you're seeing.

You can always try the most recent release here by downloading it and following the install instructions in the README file. Please let me know what you find out!

**Comment by mcoyle1960** [comment]
Version 14, and you are correct, I recently switched to lightdm from gdm3. (For some reason, I can't select a Wayland session under gdm3, but can under lightdm).

Anyway, I've switched back to gdm3 and Desk Changer is back.  Wayland was too slow anyway. :)

Thanks for the reply!
