### ISSUE TITLE
Ubuntu doesn't have `python` executable

### ISSUE THREAD

**Issue by BigE** [BigE/desk-changer#34]
Recently discovered by investigation of #33 - Ubuntu has `python3` and `python3-gi` installed by default, but does not link up a `python` executable until python2 is installed. This breaks the extension, more specifically the daemon won't start until python2 is installed. The daemon is compatible with python 2 or python 3, so it should run no matter which version or executable is installed. Currently in Version 26 of the extension, we're using a python file with a [shebang](https://github.com/BigE/desk-changer/blob/version-26/desk-changer%40eric.gach.gmail.com/desk-changer-daemon.py#L1) to execute the daemon.

I'm looking for any recommendations of how to handle this better. Currently I'm contemplating a shell wrapper script for starting the daemon. This method would work by detecting the executable to use before running python code and then executing the correct python executable. Another option, as summarized on [StackOverflow](https://stackoverflow.com/a/26056481) is to add some shell code to the python file that will help detect the correct executable. I'm open to any other ideas too.

**Comment by sp-niemand** [comment]
Hi.
I'm using the extension, thank you for creating it.
Hit this issue with my fresh Ubuntu 18.04 installation. Made a PR with a bash wrapper script solution.

**Comment by BigE** [comment]
Closing since the rewrite removes the need for python.
