### ISSUE TITLE
Hard-coded pixel values results in strange preview sizes and other irregularities

### ISSUE THREAD

**Issue by JonathanReeve** [BigE/desk-changer#35]
I have a HiDPI display, and so extensions with hard-coded pixel values look strange on my display. Desk-changer shows the preview for the next wallpaper in a fixed size that doesn't take up more than half the width of the menu. I imagine if there's a different way of specifying the width (i.e. in percentage), then that would fix the problem.

**Comment by BigE** [comment]
This is now resolved in master. I will release it with the next version release. Thanks for reporting the issue!
