### ISSUE TITLE
"Change with Profile"?

### ISSUE THREAD

**Issue by simonbcn** [BigE/desk-changer#39]
There is an option named "_Change with Profile_", what's the meaning of this? What does it do?

**Comment by BigE** [comment]
The "Change with Profile" option just allows for the wallpaper to change when the profile is changed. If this is disabled, the daemon will only rotate when the timer fires. If this is enabled, the daemon will rotate when a new profile is loaded, or when the timer fires. This could use some clarification in the settings, I'm sure. Thanks for bringing it to my attention!

**Comment by BigE** [comment]
Removed with the rewrite. Closing.
