### ISSUE TITLE
"Lock Screen Profile" displayed pasted to the profile name

### ISSUE THREAD

**Issue by simonbcn** [BigE/desk-changer#40]
I have created a lockscreen profile named "_lockscreen_" (_Why get complicated?_ :wink:  ). The popup menu shows "Lock Screen Profile" text pasted to profile name:
![screenshot](https://user-images.githubusercontent.com/428231/38358072-981eb44e-38c4-11e8-861f-0223154613a0.png)

**Comment by BigE** [comment]
Thanks for reporting! This is fixed in develop and will be released with the next version.
