### ISSUE TITLE
Displayed partially when it's integrated in system menu

### ISSUE THREAD

**Issue by simonbcn** [BigE/desk-changer#42]
When the extension is integrated in system menu, the buttons, options and literals are shown partially:
![captura de pantalla de 2018-04-06 11-05-54](https://user-images.githubusercontent.com/428231/38413245-69cfdb3c-398b-11e8-8867-278954341691.png)

**Comment by BigE** [comment]
Can you tell me what theme you're using? I don't really use the system integration, so I will have to investigate what's going on here, but this could be theme specific too. Thanks!

**Comment by simonbcn** [comment]
Actually I use this theme: https://www.opendesktop.org/p/1215199/

**Comment by BigE** [comment]
This is all kinds of messy and not working very well. There has to be some work put in to really fix this... I'm just unable to do it right now. If anyone wants to jump in and take a look at the system menu integration, it needs some love.

**Comment by simonbcn** [comment]
I think it's better suppress that option.

**Comment by sp-niemand** [comment]
:+1: to removing "integrate into system menu" option. It's probably a hassle to debug/maintain a dedicated markup for this option.

**Comment by null-dev** [comment]
I actually vote to keep that option. I don't really care how it's displayed but I don't have enough space in the top menu bar to dedicate desk-changer its own icon.

**Comment by BigE** [comment]
I'll keep the option in the extension for now. It is starting to get to a point where it's almost too broken to use, and will need some dev time sooner rather than later. I haven't taken a lot of time to work on this extension lately, so I'm not sure when this will be done on my end. Pull requests are always welcome. Thanks!

**Comment by BigE** [comment]
Closing this issue since system menu integration is not available with the rewrite. This could be a potential for a future feature request or pull request.
