### ISSUE TITLE
Error is not getting sent

### ISSUE THREAD

**Issue by slash27** [BigE/desk-changer#45]
Whenever i have some general error and then data is collected , when it is about to send the data the data is not sent and it shows me this. 
How to fix it ?
![screenshot from 2018-04-08 11-16-39](https://user-images.githubusercontent.com/37931766/38464063-c5f55c3a-3b24-11e8-8c0a-99ea1ef29498.png)

**Comment by BigE** [comment]
I'm not sure what this is. I would assume it's something Ubuntu has built in? If you're having an issue with this extension, please provide a description of the issue you're having in a new issue here. Please grab and provide any logs or errors that you are also getting with the desk-changer extension. If you need help in getting any of this, just create the issue and we'll figure out how to get the details later. Thanks!
