### ISSUE TITLE
Additional interval options

### ISSUE THREAD

**Issue by fn-ix** [BigE/desk-changer#46]
Hi!

It would be a bit more convenient, though not really necessary, to have more options regarding the time intervals, such as

* a daily rotation mode
* the possibility to select units of time in the interval mode, in addition to just having seconds

**Comment by BigE** [comment]
Great suggestions! I've been wanting to expand the interval options a lot more. I'll have to do a short write up of ideas for this and get it flushed out. Thanks for the suggestions!

**Comment by fezgit** [comment]
I would also love to see a daily rotation mode. Thanks for all the work done so far!

**Comment by fezgit** [comment]
Actually, I'm going to add to my previous comment and possibly add one more request: would it be possible to also have a new background loaded randomly at each boot? Thanks!

**Comment by Gaetan-LeGac** [comment]
A daily rotation mode is the only thing I miss from this extension.

**Comment by BigE** [comment]
New timers have been added with https://github.com/BigE/desk-changer/commit/d59ad0ff92163bd4bdcbe48af2fa93d175112d01 and are included in .
