### ISSUE TITLE
When using 'ordered' mode, errors result with first and last of the ordered images

### ISSUE THREAD

**Issue by tledford4** [BigE/desk-changer#60]
As expected, ordered mode displays the images in the path specified in Settings in alphabetical order.  On the first and last of the sorted files, however, a Gio error results when one clicks "Previous" on the first file or "Next" on the last file.

Ideally, when displaying the last ordered file, the daemon should move to the FIRST ordered file if "Next" is selected, and when displaying the first ordered file, the daemon should move to the LAST ordered file when "Previous" is pressed.

Hope this is clear.

Although the last coding I did other than shell scripting and LISP was 20 years ago, I'd be glad to take a look at the code if you can narrow down for me where to look.

**Comment by BigE** [comment]
Closing as this is no longer relevant with the rewrite.
