### ISSUE TITLE
'DeskChangerDaemon' object has no attribute 'add_main_option'

### ISSUE THREAD

**Issue by Kikadass** [BigE/desk-changer#61]
I just installed this extension and I can see it under the system menu on the top right of the screen, but it does not work. I am still in the Ubuntu background instead of choosing the images from the folder given to DeskChanger.

If I run the python script: ./desk-changer-daemon.py 

I get the following error:

Traceback (most recent call last):
  File "./desk-changer-daemon.py", line 523, in <module>
    daemon = DeskChangerDaemon()
  File "./desk-changer-daemon.py", line 46, in __init__
    self.add_main_option('version', ord('v'), GLib.OptionFlags.NONE, GLib.OptionArg.NONE,
AttributeError: 'DeskChangerDaemon' object has no attribute 'add_main_option'

OS: Ubuntu 14.04

If you need any logs please let me know where to find them(precisely) and how to get into them. 
(NOOB USER HERE)

Do you have any idea of why is this happening?
Thank you!

**Comment by BigE** [comment]
I think that you're running a version of the extension that is incompatible with your version of gnome. Check what version of gnome you have, then download the extension from the extension website for the specific version of gnome you have. 

To be honest, I haven't tried to run this extension on 14.04 in a very long time.. it likely won't work in its current state. I'm not even sure what version of the extension last supported the version of gnome running there. Thanks for the report, sorry I'm not much more help!

**Comment by Kikadass** [comment]
I am currently using GNOME Shell 3.10.4 and I believe 3.10 is the version I selected for the extension.
I know it might be an old version of the software. Do you know if it will be fixed for this version or a way of making it work? or should I just modify the xml file to create my own rotation of images and not use the extension?

**Comment by BigE** [comment]
This likely won't be fixed by me. I've been spending what little time I have on rewriting the dameon into pure JS, so the Python version is going away.

**Comment by Kikadass** [comment]
thank you for the quick response

**Comment by BigE** [comment]
Closing since a full rewrite to ES6 is now in develop
