### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by G33kNoob** [BigE/desk-changer#64]
i get error after update today

**Comment by RobinR1** [comment]
Me too.
Logging show this error:
`Extension "desk-changer@eric.gach.gmail.com" had error: TypeError: GObject.registerClass() used with invalid base class (is PopupBaseMenuItem)`

**Comment by BigE** [comment]
Hi,

Unfortunately, this version of the extension does not support gnome-shell 3.26 and the metadata.json was not updated to reflect this change. To use version 28 you must be on gnome-shell 3.30 or higher. Sorry for the inconvenience. I'll be updating the plugin site once I fix a few other issues and make another release.
