### ISSUE TITLE
desk-changer daemon is broken after update

### ISSUE THREAD

**Issue by zeparu** [BigE/desk-changer#65]
with the update yesterday the daemon cannot be disabled, neither can the mode be changed (its stuck on interval 5 seconds for me)

**Comment by G33kNoob** [comment]
me too my desk changer error after update

**Comment by BigE** [comment]
This has been fixed with the following commit - https://github.com/BigE/desk-changer/commit/b8c4d38bb7b3773483fb8e53ae40879860fced29

I'll be fixing a few other things and then making a release. Thanks for the report!
