### ISSUE TITLE
Gnome Shell 3.36 - UI Error - Daemon working

### ISSUE THREAD

**Issue by fdinardo** [BigE/desk-changer#67]
Hi, thanks for this extension.

Archlinux recently updated gnome to 3.36 and this extension is half-working.
The problem is that the Daemon is running correctly but the UI is not working.

Here is the error message from the LG console:
```
Error: Invalid value 'undefined' for property state in object initializer.
```

Hope this helps you

**Comment by BigE** [comment]
Hi,

I haven't had a chance to pull 3.36 and test anything yet. I'll get there soon... will update again once I've got an idea of what's actually going on here. Thanks for the report!

**Comment by fdinardo** [comment]
Every gnome update breaks most of the major extensions we are used to, I understand keep the extensions working every time a new version comes up can be hard. For this reason I would like to help contributing. Let me know if I can help you.

**Comment by BigE** [comment]
@fdinardo You're always more than welcome to submit any kind of PR to address the issue. I've got 3.36/Arch on my laptop at home, just not enough time to commit to debugging and fixing yet. Thanks!

**Comment by fdinardo** [comment]
Yeah, I would like to help, but the very big problem is I don't know how to debug the extension.
LG console is showing a too generic error, no clues on where this happens, no clue on which file is generating the error. 

Do you have any links where I can look at to learn how to debug the extension?

**Comment by BigE** [comment]
`journalctl -xe /usr/bin/gnome-shell` 
you can use this to see gnome-shell logging, which contains a bit more info. I was able to pull this trace, but there are other errors too... 

> Mar 12 08:09:13 arch.laptop.localhost gnome-shell[819]: JS ERROR: Extension desk-changer@eric.gach.gmail.com: Error: Invalid value 'undefined' for property state in object initializer.
>                                                         _init@resource:///org/gnome/shell/ui/popupMenu.js:324:15
>                                                         _init@resource:///org/gnome/shell/ui/popupMenu.js:361:24
>                                                         _init@/home/eric/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/ui/popupMenu.js:313:15
>                                                         _init@/home/eric/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/ui/panelMenu.js:23:31
>                                                         enable@/home/eric/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/extension.js:120:14
>                                                         _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
>                                                         loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
>                                                         _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
>                                                         collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
>                                                         _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
>                                                         _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
>                                                         _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
>                                                         init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
>                                                         _initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
>                                                         start@resource:///org/gnome/shell/ui/main.js:138:5
>                                                         @<main>:1:47

It looks like there's a bit of a line to follow here... 
https://github.com/BigE/desk-changer/blob/master/desk-changer%40eric.gach.gmail.com/ui/popupMenu.js#L313
https://github.com/BigE/desk-changer/blob/master/desk-changer%40eric.gach.gmail.com/ui/panelMenu.js#L23
https://github.com/BigE/desk-changer/blob/master/desk-changer%40eric.gach.gmail.com/extension.js#L120
It might be a gettext problem... seems like the label is empty. I'm not sure why this would be? Hope that helps you down a path. I'll get there eventually :smile:

**Comment by fdinardo** [comment]
Thanks this helped me. Actually I am using this `journalctl /usr/bin/gnome-shell -f -o cat` to getting the error at runtime.
```
=============================
label: Notifications
key: notifications
settings: [object instance wrapper GType:Gjs_desk-changer_eric_gach_gmail_com_convenience_DeskChangerSettings jsobj@0x22fbb3e0c80 native@0x55e766c94dc0]
=============================
JS ERROR: Extension desk-changer@eric.gach.gmail.com: Error: Invalid value 'undefined' for property state in object initializer.
```
I just wanted to check those variables, and they are not empty.
the call that fails is `super._init(label);`
Now I am a bit confused. I am not sure if it's the `_init` function called in that way, or the error happens inside the `_init`...

What I can tell for sure is label is not empty.

**Comment by BigE** [comment]
Found it... https://github.com/GNOME/gnome-shell/commit/4e26e0e53c9114c156749ed570e77e9dbf57187f is the change that caused the error. It's a pretty simple fix, since it just needs to be passed through the constructor. I'll have a fix shortly... but other work needs to be done to update it for 3.36 still. Thanks!
