### ISSUE TITLE
Error Loading Extension

### ISSUE THREAD

**Issue by retesta** [BigE/desk-changer#69]
Get that error message whether I install it manually or from extensions.gnome.org
Zorin OS 15.2
GNOME Shell 3.30.2
Have the latest python-gi package installed

![Screenshot from 2020-06-22 13-46-39](https://user-images.githubusercontent.com/64700989/85314943-b9ecd480-b4a9-11ea-93ab-4eb306b0b65e.png)
![Screenshot from 2020-06-22 13-58-21](https://user-images.githubusercontent.com/64700989/85314954-beb18880-b4a9-11ea-9cd6-d957828de149.png)

**Comment by BigE** [comment]
Hi @retesta,

If you could, open a terminal and run the command `journalctl -xe /usr/bin/gnome-shell` and see if you can find some specific error messages here that pertain to the extension. You're going to be looking for anything that contains the extension ID which is `desk-changer@eric.gach.gmail.com` Please let me know if you have any questions.

**Comment by retesta** [comment]
`Extension "desk-changer@eric.gach.gmail.com" had error: TypeError: GObject.registerClass() used with invalid base class (is PopupBaseMenuItem)`
Had that same error show up a few times

**Comment by Episodio1** [comment]
> `Extension "desk-changer@eric.gach.gmail.com" had error: TypeError: GObject.registerClass() used with invalid base class (is PopupBaseMenuItem)`
> Had that same error show up a few times

Same here with Ubuntu 18.04

**Comment by BigE** [comment]
@retesta @Episodio1 - thank you both! can you both tell me what version of the extension you have installed? you can check this by going to the extensions folder and opening the metadata.json file. Thanks!

**Comment by retesta** [comment]
Version 18

**Comment by Episodio1** [comment]
Version 29.
Ubuntu 18, Gnome 3.28.2

**Comment by arpagon** [comment]
Hi, this work for me on Ubuntu 20.10 and gnome 3.38

```
git clone -b develop git@github.com:BigE/desk-changer.git
cd desk-changer
make all
make install
```

**Comment by BigE** [comment]
This should be fixed by the [Version 30](https://github.com/BigE/desk-changer/releases/tag/version-30) release. If you continue to experience issues, please open a new issue with new details. Thanks!
