### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by mohegan** [BigE/desk-changer#74]
This extension works well but it uses many CPU. For me, the process takes 25% of CPU. It's a lot !

**Comment by BigE** [comment]
Hi @mohegan, can you tell me what version of the plugin you're using by checking the `metadata.json` file in the extension folder? It should be located in `$HOME/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/` Thanks!

**Comment by mohegan** [comment]
Version : 19 

{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Simple wallpaper changer with multiple profile support. Supports integration into the system menu or its own panel icon. The daemon is written in Python and runs independently of the extension.",
  "gettext-domain": "desk-changer",
  "name": "Desk Changer",
  "settings-schema": "org.gnome.shell.extensions.desk-changer",
  "shell-version": [
    "3.30",
    "3.34",
    "3.32",
    "3.36",
    "3.38"
  ],
  "url": "https://github.com/BigE/desk-changer/",
  "uuid": "desk-changer@eric.gach.gmail.com",
  "version": 19
}

**Comment by BigE** [comment]
Great thanks! It looks like you're using the most recent version, so the daemon should be a `gjs` process running in the background. Can you share some of your settings config with me? Screenshots of the settings windows are just fine, so I can get an idea of what your configuration is.

**Comment by mohegan** [comment]
![Capture d’écran de 2021-01-07 11-02-42](https://user-images.githubusercontent.com/635456/103879397-14f9b800-50d8-11eb-997b-334d96a14446.png)
![Capture d’écran de 2021-01-07 11-02-46](https://user-images.githubusercontent.com/635456/103879408-19be6c00-50d8-11eb-9fc9-5cfdfb63b3ff.png)
![Capture d’écran de 2021-01-07 11-02-51](https://user-images.githubusercontent.com/635456/103879416-1c20c600-50d8-11eb-85c2-2060cc5040eb.png)
![Capture d’écran de 2021-01-07 11-03-04](https://user-images.githubusercontent.com/635456/103879419-1d51f300-50d8-11eb-9c0a-479a31661515.png)

**Comment by mohegan** [comment]
Nothing extraordinary !

**Comment by BigE** [comment]
@mohegan can you run the daemon yourself, with debugging enabled? You will have to change the debug setting to true for the extension, then run the daemon from the command line. You will also have to stop the daemon from the extension first. I recommend using `dconf-editor` to change the settings, like the [README.md](https://github.com/BigE/desk-changer/blob/1c540541868a0753f504899bd99421a430dd97f9/README.md) says using `GSETTINGS_SCHEMA_DIR=~/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/schemas/ dconf-editor`

Once you've done that, you can start the daemon from the command line using the command `gjs ~/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/daemon/server.js` Once you've got the output, feel free to paste it all here. I'm not sure why the daemon would be using CPU with those settings, at all. I'm interested to see what happens.

Thanks!

**Comment by BigE** [comment]
Hi,

I'm closing this bug as there has been no feedback and several version updates. If you're still having the issue, please file a new report with new information.

Thanks!
