### ISSUE TITLE
I would be very interested in packaging it into AUR to make it easier for archLinux users to use!

### ISSUE THREAD

**Issue by Chao-zhi** [BigE/desk-changer#77]
There are many GNOME Shell extensions that become a package in the Arch User Repository (AUR). Your extension is also excellent. I'd like to pack him up to the AUR, which may require your authorization.

**Comment by BigE** [comment]
I'm totally fine with it. I'd even be willing to collaborate the effort, if needed. Please let me know what I can do to help you get it there. Thanks!

**Comment by Chao-zhi** [comment]
I have packaged this plugin into AUR and it works normally at present.
https://aur.archlinux.org/packages/gnome-shell-extension-desk-changer/

**Comment by BigE** [comment]
Closing since you've opened the AUR package. Thank you for doing this!
