### ISSUE TITLE
Gnome shell 40 update?

### ISSUE THREAD

**Issue by wuqso** [BigE/desk-changer#79]
Very nice extension but outdated for gnome shell 40. When will there be an update?

**Comment by BigE** [comment]
Hi @wuqso 

I don't have an ETA for Gnome 40 support yet. If anyone would like to help get this kick started, I'd love the help. Otherwise, it'll happen once I have a chance to dig back in.

Thanks!

**Comment by Christopher876** [comment]
So I was messing around with it the other day. I don't know much about gtk development yet. However, just updating the version supported allows it to start changing the wallpaper. As far as I was looking at the source. hbox.pack is the main method that needs to be replaced with the newer GTK 4 methods to get the GUI working.

**Comment by BigE** [comment]
Hi All,

With the most recent [commit](https://github.com/BigE/desk-changer/commit/f85c7b1d7df8ffaf4fe4c374722f8a3c64bcc81f) to develop, things seem to be working much better with Gnome Shell 40. The prefs aren't formatted yet, but the window loads and everything mostly seems to work. I'll make more updates as I can get to them.

**Comment by BigE** [comment]
It looks like the [prefs](https://gjs.guide/extensions/upgrading/gnome-shell-40.html#prefs) now use a template class? This will have to be done and adapted, before things will properly work. I'm not sure if it's absolutely needed, but it would probably make things easier to maintain in the future, so I'm willing to venture down this road.

**Comment by BigE** [comment]
Full support for Gnome Shell 40 has been added in [Version 31](https://github.com/BigE/desk-changer/releases/tag/version-31)
