### ISSUE TITLE
Option to remove or disable shortcuts?

### ISSUE THREAD

**Issue by joshuar** [BigE/desk-changer#8]
Great extension, but it would be nice to have a way to disable the global shortcuts, as this can interfere with other application specific shortcuts.  Also, these shortcuts are fairly generic and seem to be commonly used by other applications (i.e., many word processors allow you to skip over words with Crtl-left/right).

**Comment by BigE** [comment]
Thanks for the suggestion! I've already implemented the fix in a previous report #4 but it hasn't made it up on the gnome extension site yet. Even though the first version of my extension was approved, they requested the daemon to be rewritten in python/ruby, something not binary, so I'm preoccupied with that request before this change will be released on the extension site. You're free to download the extension and build it yourself from here if you want the update. Thanks again!
