### ISSUE TITLE
Slowing down and stacking on Wayland and not working on XORG

### ISSUE THREAD

**Issue by Andres-Chandia** [BigE/desk-changer#81]
The settings of extension desk-changer@eric.gach.gmail.com had an error:
```
GLib.FileError: Falló al abrir el archivo «/usr/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/resources/org.gnome.Shell.Extensions.DeskChanger.gresource»: open() falló: No existe el archivo o el directorio
```

Stack trace:
```
@/usr/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/_deskchanger.js:275:14
@/usr/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/prefs.js:10:1
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

but the directory is there:

cht@ubucht2:~$ ls /usr/share/gnome-shell/extensions/
desk-changer@eric.gach.gmail.com  desktop-icons@csoriano  impatience@gfxmonk.net  panel-osd@berend.de.schouwer.gmail.com  ubuntu-appindicators@ubuntu.com  ubuntu-dock@ubuntu.com
cht@ubucht2:~$ ls /usr/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/
common  convenience.js  daemon  _deskchanger.js  extension.js  locale  metadata.json  prefs.js  resources  schemas  service.js  ui

**Comment by BigE** [comment]
Hi @Andres-Chandia

How did you install this extension? It looks like you're missing a resource file, which should be included in the extension website. However, if you grabbed it from github, they should be compiled before they can be used.

**Comment by Andres-Chandia** [comment]
Well, now I reinstall it, just to try, and it did work..... sorry and thanks...

**Comment by BigE** [comment]
No problem. I'm glad it's working for you now. Please, enjoy!
