### ISSUE TITLE
Feature Request: Disable Statusbar Icon

### ISSUE THREAD

**Issue by DualityKyle** [BigE/desk-changer#84]
Would it be possible to add an option to disable the statusbar icon for the extension? This is the type of extension where I don't need something in the statusbar for it, if I need to change something I'm happy to go into the extensions menu.

This would help keep the statusbar clean and tidy for those of us who care about that sort of thing :)

**Comment by BigE** [comment]
Hi @DualityKyle,

I used to have a feature where it integrated into the system menu. I would propose reviving this feature to implement something like you suggest. It wouldn't remove the functionality completely, but minimize it into its own submenu in the system menu.

I'll look into implementing this again soon.

**Comment by DualityKyle** [comment]
Thanks for the quick reply! That would definitely be an acceptable compromise, looking forward to it! Appreciate you taking it into consideration :)

**Comment by DualityKyle** [comment]
So, this might be able to be closed. I did a new install and installed the extension. I haven't had it installed since I was waiting for a change. But I noticed that if I set the daemon to autostart, and kept it running, I could disable the extension and still have it cycle through my wallpapers, without the topbar icon displaying.

So sounds like this may be a workaround :)

**Comment by BigE** [comment]
@DualityKyle Thanks for the update. While this may be a good solution for you, I want to still provide a way to interact with the daemon without necessarily having an extension icon. I'll open a new ticket soon and reference this one, so we can track new development there. 

Thanks again!
