### ISSUE TITLE
Gnome 41 compatibility

### ISSUE THREAD

**Issue by belegdol** [BigE/desk-changer#85]
The extension is reported as outdated on gnome 41.

**Comment by BigE** [comment]
Thanks for the report @belegdol. I'll get to it as soon as I can. I'm hoping it's just as simple as updating the metadata.json file.

**Comment by zinkst** [comment]
Just tested editing **metadata.json** manually on Gnome 41, Fedora 35, as suggested in the [commit](https://github.com/BigE/desk-changer/commit/54f427a9f1ff738b53a53cd2c4806cd7539abf58)
Works for me

**Comment by BigE** [comment]
@zinkst Thanks for the feedback! I'll try to do my own tests soon... whenever Arch decides to upgrade packages and I finally pull them 😆 

@belegdol Could you also confirm this change works?

I'll prepare a release later this week if it's that simple. Thank you both!

**Comment by belegdol** [comment]
> @zinkst Thanks for the feedback! I'll try to do my own tests soon... whenever Arch decides to upgrade packages and I finally pull them laughing
> 
> @belegdol Could you also confirm this change works?
> 
> I'll prepare a release later this week if it's that simple. Thank you both!

Yes, adding 41 to metadata.json seems to be sufficient.

**Comment by BigE** [comment]
Releasing [version-33](https://github.com/BigE/desk-changer/releases/tag/version-33) to support Gnome 41. Thank you @belegdol and @zinkst for helping report and test!! 

I'll release this to the extension site as well.
