### ISSUE TITLE
Extension working partially

### ISSUE THREAD

**Issue by Dani-Default** [BigE/desk-changer#9]
Hello, I installed your extension on my ubuntu gnome 16.04 (running gnome-shell 3.20.4) and it worked like a charm. After I manually reinstalled it (was trying to find out the reason why LCtrl+Left shortcut wasnt working), the Daemon(?) isnt working properly. Whenever I switch the 'show daemon status' toggle under the preferences, the switch animates and everything, but fails to do anything. Switching the 'daemon on' toggle also doesnt do anything. 

I tried uninstalling everything and reinstalling multiple times, but with no luck. My uninstall method consists in just deleting the @folder under gnome-shell/extensions directory, hopefully it is the correct way of doing things. 

To further describe the problem, the extension UI used to show a preview of the next wallpaper to be used, this is gone and is nowhere to be found. Also selecting the open next wallpaper location button isnt doing its job. Choosing open current wallpaper does work fine and all other buttons seem to animate correctly. 

Not sure if its important, but everytime I deleted/reinstalled the extension, it somehow remembers all my profiles and picture paths, although I thought I erased all files; could you let me know where this information is stored? 

I hope Im using the 'Issues' tab correctly, otherwise I would be happy if you could point me in the right direction to post my question and you can close/delete this issue.

Thanks in advance 

Edit: Im using version 13 of the extension

**Comment by BigE** [comment]
Hmm... there could be an error with the daemon running. I've built in debugging so you can run it manually and see what's going on. To run it with debugging output, you should be in the extension directory:
`cd $HOME/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com`
Then run the daemon manually with the following command:
`G_MESSAGES_DEBUG=all python desk-changer-daemon.py`
If the daemon fails to start, please copy and paste all the output here to this ticket.

While running it, if you get an error like so `Failed to register: Unable to acquire bus name 'org.gnome.Shell.Extensions.DeskChanger.Daemon'` then the daemon is possibly already running in the background somehow and the extension doesn't see it. If this is the case, you can run the following command to view the possible process `ps aux | grep -v grep | grep desk-changer-daemon.py` and copy/paste the output here and I'll see what I can figure out.

If all the above fails, you should check your gnome-shell logs to see if there is a possible error in the extension itself. If you're using the default systemd in Ubuntu, you can get them by issuing the following command `sudo journalctl -xe /usr/bin/gnome-shell` ... I'm sure you can grep for the extension, but you'll have to look through here and copy/paste the relevant logging info from the extension itself.

Eithe way, once you get more information, provide it here and I'll see what I can do to help you get things up and going. All of the information for the settings is stored in the gnome-settings daemon. You can access them by using `dconf` and going to `/org/gnome/shell/extensions/desk-changer/` where all the settings are stored. Thanks!

**Comment by Dani-Default** [comment]
Thanks for the response! 

The debuging of the daemon showed this report:

Traceback (most recent call last):
  File "desk-changer-daemon.py", line 119, in do_dbus_unregister
    self._debug('::dbus_unregister')
  File "desk-changer-daemon.py", line 233, in _debug
    self._log(GLib.LogLevelFlags.LEVEL_DEBUG, message, *args)
  File "desk-changer-daemon.py", line 394, in _log
    GLib.log_variant(None, level, fields)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.GLib' object has no attribute 'log_variant'
fish: “env G_MESSAGES_DEBUG=all python…” terminated by signal SIGSEGV (Address boundary error)


While the gnome-shell-logs showed this one:

Traceback (most recent call last):
  File "/home/x/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/desk-changer-daemon.py", l
    self._debug('::dbus_register')
  File "/home/x/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/desk-changer-daemon.py", l
    self._log(GLib.LogLevelFlags.LEVEL_DEBUG, message, *args)
  File "/home/x/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/desk-changer-daemon.py", l
    GLib.log_variant(None, level, fields)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.GLib' object has no attribute 'log_variant'

Could this faulty(?) Library be causing the issue or is this a normal log?

Thanks again for the response and all the tips to identify the problem.

**Comment by BigE** [comment]
I believe this error is due to GLib.log_variant being a relatively new function. After some quick poking, I was able to reveal https://bugzilla.gnome.org/show_bug.cgi?id=770971 which indicates that log_variant is a new addition to help aid pygobect and gjs. I'll do some digging as soon as I have some free time to seek out a new replacement method that is backwards compatible, then everything should be back and working for you. Thanks!

**Comment by BigE** [comment]
Gah, didn't mean for this to get closed... I still consider it an open issue since my fix is to basically remove logging from those that don't have GLib.log_variant()

**Comment by JesusFromHellz** [comment]
Hello. I'm using desk-changer since some time ago, and recently got some issues.
Today (just now) I figured out why it wasn't working. My problem was exactly like the guy who opened this issue, clicking to start daemon toggle but doesn't start, then back to off place.
Now I figured out why it wasn't working:
Recently I've changed a configuration about my partition which have the images that were loaded in the extension, and when I changed, it changed the directory (from media to mnt), and now, I was seeing my profile in desk-changer and saw the directorys were still the old ones (pointing to /media/), then I changed them to /mnt, chose the new ones, saved the profile, closed the settings tab, came back to the extension and after clicking in daemon to start, it worked. I don't really now why it wasn't working whey it had no images, maybe some safe configuration, but seemed to be that. If someone else have this issue, can try checking this.

Sorry for my bad english :v 
Cheers

**Comment by BigE** [comment]
Thanks for the tip! I'll have to check the daemon and make it raise an actual error to the extension when that happens. Seems like the end user should know why something isn't working ;)

**Comment by Dani-Default** [comment]
I installed the latest version (v.16) and works way better. I get the previews if I restart the shell, but only if I do so. The daemon is initializing just fine. A problem that has arisen though is, that i cant control the picture change delay. I put a number in the field (in my case is 43200 seconds for 12 hours swap time) but the extension doesnt seem to acknowledge it and changes the background every few minutes. Both shortcut keys (for previous and next) seem to be working now, which is fantastic. 

Thanks for the continuous development! 

PS: not related to this issue, but could you get us some insight if the system menu integration feature is far off?

**Comment by BigE** [comment]
Thanks for the feedback! I'll look into the timer problem. System menu integration is a work in progress... what I've got done is in the branch I've pushed.. no more really than exploration unfortunately. I'll work on it when I can, but I make no promises :) thanks again for the feedback, it really helps!

**Comment by BigE** [comment]
I've finally found a solution that allows for logging. I'm feeling a bit dumb for not noticing it before, but its resolved and will be released in the next version. Thanks for the bug report!
