### ISSUE TITLE
Error in GNOME 3.38.5 due to setting dark mode

### ISSUE THREAD

**Issue by anitschke** [BigE/desk-changer#91]
I am using GNOME 3.38.5 and am seeing the following error:

Gio.IOErrorEnum: GDBus.Error:org.gnome.Shell.Extensions.DeskChanger.Daemon.Start: GSettings key picture-uri-dark not found in schema org.gnome.desktop.background

It looks like this was caused by adding support for the new dark mode settings: https://github.com/BigE/desk-changer/commit/0ab807d7ffdfca537dfb184bb9e575bbda30a226

Commenting out this line of code seems to fix the issue for me. I did some digging around in the Gio settings doc to see if there is a way check if a Dconf schema has a key so we could only set it when the schema has that key. I found or not. I found [SettingsSchema.has_key](https://gjs-docs.gnome.org/gio20~2.66p/gio.settingsschema#method-has_key) but I don't know how to go from a Settings to a SettingsSchema.

**Comment by rodneydup** [comment]
Same on gnome 3.38.4... Maybe there could be a conditional that only includes that line if the gnome version is 42 or greater?

**Comment by Andres-Chandia** [comment]
I had the same issue, reinstalling it make it work again....

**Comment by BigE** [comment]
This is fixed in develop. A release will be coming soon, just trying to make sure I've gotten all the things before doing so. Thanks for reporting!
