### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by belegdol** [BigE/desk-changer#95]
Smoke test indicates adding 44 to metadata.json is sufficient.

**Comment by BigE** [comment]
Support added with pull request https://github.com/BigE/desk-changer/pull/96 I'll be releasing this to the extension site ASAP. Thanks for reporting!

**Comment by 05storm26** [comment]
@BigE This is still not released. Could you please release this on github and on the gnome shell extension website as v36?
